### ISSUE TITLE
JS - Remove JS Media Queries and use CSS

### ISSUE THREAD

**Issue by rcass** [jaridwarren/instanews-app#12]
Okay, this will be hard to explain in full because there is a bit to be said about this section.

Basically, lines from 19-82 are for the most part unnecessary and not performant. 
https://github.com/jaridwarren/instanews-app/blob/5cfc9ad3f536b9c2f2c72cbec4e484d6b45924e6/js/index.js#L19-L82

One or two .css() methods is ok, but responsiveness should be done via CSS.

Since you have so much `.css()` instead, you could addClass. In the CSS for that class have all the breakpoints that you want. Thus removing these many lines of JS.  

I closed this issue because address this would make this one resolved as well #11

**Comment by jaridnft** [comment]
@rcass since the styling is dynamic, isn't the best way to change the styles with JS? I'm not only checking media queries but if the user has selected a certain option as well.

**Comment by rcass** [comment]
Ok to put it simply, you’re solving a problem that doesn’t need to be solved because you don’t need JavaScript for.

Okay to drive further:
*Performance* - Using JS to do what CSS can do is ultimately not performant. CSS DOM changes get their own thread so are faster and don't block your scripts.

*Hidden Problems* - Screen size detection using JS comes with some serious gotchas and also should be avoided.

Anyhow, looking at your code seems you are solving a problem that is not a requirement or anything. 🤷‍♀️ So you can choose to keep this but to someone reviewing code, it will look a bit off given that it seems like unnecessary JS (and for the reasons above as well).

**Comment by jaridnft** [comment]
Deleted `.css()` calls and using `.addClass()`/`.removeClass()` to achieve functionality on `es6-branch`.
