### ISSUE TITLE
JS - Using variables and +=

### ISSUE THREAD

**Issue by rcass** [jaridwarren/instanews-app#13]
In `index.js` you might want t consider using variables, espcially for this items you find you are calling over and over or reassigning/adding to.

For example:
https://github.com/jaridwarren/instanews-app/blob/5cfc9ad3f536b9c2f2c72cbec4e484d6b45924e6/js/index.js#L113-L123

Something like this maybe:
```
let items;
              
items += '<div class="story-cell" onclick="openInNewTab(\'' ';
items += storyUrl;
items += '\');" style="cursor: pointer;">';
items += '<p class="story-text">';
items += data.results[key].abstract;
items += '</p></div>';

$(".stories").append(items);
```

**Comment by jaridnft** [comment]
@rcass template literal would be best here, no?

**Comment by rcass** [comment]
Yes it would 🙌  #es6forthewin

**Comment by jaridnft** [comment]
Switched over to template literals on `es6-branch`.
