### ISSUE TITLE
JS - Use JS to create <a href="">

### ISSUE THREAD

**Issue by rcass** [jaridwarren/instanews-app#15]
In the generated markup, I noticed that there doesn't seem to be any link tags generated.

Instead, you have used JS to create the functionality of an anchor tag without really using one.

I recommend using an anchor tag and then the markup will be more accurate (semantic and accessible as well!) and then you don't need the extra code at the top of your js (to open in a new window).

https://github.com/jaridwarren/instanews-app/blob/5cfc9ad3f536b9c2f2c72cbec4e484d6b45924e6/js/index.js#L1-L5

**Comment by jaridnft** [comment]
Got rid of `<div>` containers and replaced with `<a>` containers using `display: block`. Used anchor tag with attribute `target="_blank"` to open in new window.
