### ISSUE TITLE
JS - Try the hover in CSS

### ISSUE THREAD

**Issue by rcass** [jaridwarren/instanews-app#16]
Seem like this bit of code:
https://github.com/jaridwarren/instanews-app/blob/5cfc9ad3f536b9c2f2c72cbec4e484d6b45924e6/js/index.js#L128-L133

Seem like it is for the stretch goal `Use CSS3 transitions to show and hide the article abstract on hover`. For this stretch goal, it should be mostly achieved through CSS, and with no JS.

**Comment by jaridnft** [comment]
Respect the fact that the stretch goal's intention was for a CSS transition, but I'm deciding to keep it in JS. I've modified the code to "slide up" smoother.
```javascript
$(".story-cell").hover(
            function() {
              $(this)
                .children()
                .slideToggle();
            },
            function() {
              $(this)
                .children()
                .slideToggle();
            }
          );
```
