### ISSUE TITLE
JS - Instead of hide/show, just simply empty

### ISSUE THREAD

**Issue by rcass** [jaridwarren/instanews-app#17]
I noticed this in your code:
https://github.com/jaridwarren/instanews-app/blob/5cfc9ad3f536b9c2f2c72cbec4e484d6b45924e6/js/index.js#L93-L97

I am unsure if this is really necessary. You don't really need to hide/show the stories or footer.
1) *Footer* - Remains on the page even when the loading gif is present
2) *Stories* - You don't need to show and hide, you would just be appending things to it when necessary, and when it is empty nothing would be showing anyways. When a selection is made, the loading gif is shown but there is nothing in the stories area yet, so nothing would show there.
You will just need to empty the area on selection change. 
For example:
`$stories.empty();` to reset it before the ajax call.

**Comment by jaridnft** [comment]
I decided to hide the "Footer" as if it isn't hidden, it will show up above the loading gif once "Stories" is hidden.
You are correct, I don't have to hide "Stories" at all since I'm clearing them on selection change regardless. These changes will be reflected when I merge `es6-branch`.

**Comment by jaridnft** [comment]
Realized the loader gif was placed below the footer in `index.html`, I've moved it above and removed `$("footer").hide()` as per your original suggestion.

https://github.com/jaridwarren/instanews-app/blob/5cfc9ad3f536b9c2f2c72cbec4e484d6b45924e6/index.html#L48-L57
