### ISSUE TITLE
JS - Instead of `complete` consider `.always()`

### ISSUE THREAD

**Issue by rcass** [jaridwarren/instanews-app#18]
Looking at your code, since it seems you always want to hide the loader gif no matter what the response (stories or an error), I recommend just placing that within always function.

The `.always()` function usually is written after the `.fail()` function, and will run regardless is data is retrieved or not. Since `complete` in this context is doing something very similar to `.always()` this is just a recommendation.

Just make things more readable to others, since the use of `.always()` is very common.

This would look something like this:
```
        .always(function() {
          $loader.hide();
        });
```

**Comment by jaridnft** [comment]
`complete:` in the context of `.ajax()` only executes if the ajax request is successful. With that considered, I think `complete` works better since I only want to hide the loader gif once data comes back successfully.
