### ISSUE TITLE
Filter news results to 12 only containing images. 

### ISSUE THREAD

**Issue by vbertoletti** [jaridwarren/instanews-app#3]

**Comment by jaridnft** [comment]
It already does.

**Comment by rcass** [comment]
^ When replying to issue comments, it will help the person who issued the comment understand your reply by linking to a certain code block (just add the permalink to your issue comment)

**Comment by jaridnft** [comment]
For completeness, here is the logic that prints out only 12 stories:

https://github.com/jaridwarren/instanews-app/blob/5cfc9ad3f536b9c2f2c72cbec4e484d6b45924e6/js/index.js#L103-L125

**Comment by rcass** [comment]
^ Thanks for adding this! Since code can be written in a plethora of ways, this could help the issuer understand a new code solution to the problem they may not have thought of 🙌
