### ISSUE TITLE
Move style to Sass or inject via JS instead of inline

### ISSUE THREAD

**Issue by rcass** [jaridwarren/instanews-app#6]
This is just a matter of opinion and makes things easier to track (esp. for the person just trying to understand your project).

Anyhow, I think the inline style on the loading gif:
https://github.com/jaridwarren/instanews-app/blob/5cfc9ad3f536b9c2f2c72cbec4e484d6b45924e6/index.html#L55
Can be added via CSS (well through a Sass partial) or via JS. JS is my second choice because I think just plain ol' CSS should be enough.

It will make it easier for others to understand where styles are coming from if we put it in the same place if possible.

**Comment by jaridnft** [comment]
Moved `.loader` styling to `partials/_main.scss`.
