### ISSUE TITLE
Sass - Place Variables (in _mixins.scss into _variables.scss)

### ISSUE THREAD

**Issue by rcass** [jaridwarren/instanews-app#8]
Since these are variables I think it makes organizational sense to put them in `_variables.scss`

https://github.com/jaridwarren/instanews-app/blob/5cfc9ad3f536b9c2f2c72cbec4e484d6b45924e6/sass/partials/_mixins.scss#L1-L3

**Comment by jaridnft** [comment]
Moved to `partials/_variables.scss` in `es6-branch`.
