### ISSUE TITLE
Sass - Remove all styles from style.scss

### ISSUE THREAD

**Issue by rcass** [jaridwarren/instanews-app#9]
I noticed you put a majority of the project styles in the styles.scss. The structure of Sass in this project is that the styles will be all in partials, and the *only* things inside the style.scss is the import statements.

So basically, the style.scss is going to be quite short (6-10 lines) of just import statements.
https://github.com/jaridwarren/instanews-app/blob/5cfc9ad3f536b9c2f2c72cbec4e484d6b45924e6/sass/style.scss#L1-L3

The styles that are currently in there just need to be moved into appropriate partials. For example, maybe you want to create a content or body partial 👍

**Comment by jaridnft** [comment]
@rcass you mentioned this in class, but I didn't see the point of having style.scss empty of styling? I understand for larger projects, however.

**Comment by rcass** [comment]
Ya, this was intended to be the baby step version to get everyone use to the structure before moving on to a larger project.

**Comment by jaridnft** [comment]
Removed everything but `@import` statements from `style.scss` in `es6-branch`.
